-- UI component default parameters
UIDefaults = {
  Button = {
    width = 200,
    height = 200,
    font_color = {1, 1, 1},
    color = {0.05, 0.05, 0.05, 1},
    font_size = 200,
    scale = {x = 0.2, y = 0.2, z = 0.2},
    click_function = "OnUpdate", -- Should always be replaced
    label = "X",
    position = {0, 0, 0}
  },

  Text = {
    type = "3DText",
    rotation = {90, 0, 0},
    font_size = 50
  }
}
